Implement search solr cache EBS volumes cleanup schedule
ministryofjustice/hmpps-delius-alfresco-shared-terraform pull request #430
Opened 2023-05-30 07:08 UTC by silvianahorga-al

Ticket no. https://dsdmoj.atlassian.net/browse/NIT-663

2023-05-30 09:25 UTC, kylehodgetts requested changes

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/cloudwatch.tf
> +}
```suggestion
}

```

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/cloudwatch.tf
> +    FunctionName = "${aws_lambda_function.ebs-vols-cleanup-scheduler.function_name}"
Does this need to be quoted?

Can we get away with this?
```suggestion
    FunctionName = aws_lambda_function.ebs-vols-cleanup-scheduler.function_name
```

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/cloudwatch.tf
> +    Resource     = "${aws_lambda_function.ebs-vols-cleanup-scheduler.function_name}"
likewise

```suggestion
    Resource     = aws_lambda_function.ebs-vols-cleanup-scheduler.function_name
```

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/data.tf
> +}
```suggestion
}

```

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/lambda.tf
> +  output_path        = "${path.module}/files/alfresco-ebs-vols-cleanup.zip"
I see you have committed the Zip file containing the code. If the code changes, will Terraform detect the a new version of the file and recreate the zip file?

asking because I couldnt see anything related to that in the TF docs for archive_file

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/lambda.tf
> +  schedule_expression = var.cleanup_scheduler_expression
Since this is not a module and the comment says its a daily job, I think we can hardcode the expression here and have one less variable. Upto you though

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/lambda.tf
> +resource "aws_cloudwatch_event_target" "cleanup_scheduler_event_target" {
Needs `terraform fmt`

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/lambda.tf
> +  arn      = "${aws_lambda_function.ebs-vols-cleanup-scheduler.arn}"
```suggestion
  arn      = aws_lambda_function.ebs-vols-cleanup-scheduler.arn
```

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/lambda.tf
> +  function_name = "${aws_lambda_function.ebs-vols-cleanup-scheduler.function_name}"
```suggestion
  function_name = aws_lambda_function.ebs-vols-cleanup-scheduler.function_name
```

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/lambda.tf
> +  source_arn    = "${aws_cloudwatch_event_rule.cleanup_scheduler_event_rule.arn}"
```suggestion
  source_arn    = aws_cloudwatch_event_rule.cleanup_scheduler_event_rule.arn
```

2023-05-30 09:25 UTC, kylehodgetts commented on alfresco-search-solr/templates/policies/ebs-vols-cleanup-policy.tpl
> +}
```suggestion
}

```

2023-05-30 09:25 UTC, kylehodgetts commented on monitoring/output.tf
> +}
```suggestion
}

```

2023-05-30 16:32 UTC, silvianahorga-al commented on alfresco-search-solr/lambda.tf
> +  output_path        = "${path.module}/files/alfresco-ebs-vols-cleanup.zip"
Yes, it should detect the changes and recreate the zip file (there are similar config for other lambda functions we're using)

2023-05-31 07:27 UTC, silvianahorga-al commented on alfresco-search-solr/lambda.tf
> +  schedule_expression = var.cleanup_scheduler_expression
Hours can still be changed so I would keep the variable

2023-05-31 07:27 UTC, silvianahorga-al commented on alfresco-search-solr/lambda.tf
> +resource "aws_cloudwatch_event_target" "cleanup_scheduler_event_target" {
done

2023-05-31 08:04 UTC, kylehodgetts requested changes
Small change to remove the DryRun flag when deleting volumes

by the way, what's are all these .history Makefiles?

2023-05-31 08:04 UTC, kylehodgetts commented on alfresco-search-solr/volume_cleanup_lambda/volume_cleanup.py
> +        client.delete_volume(VolumeId=volume['VolumeId'], DryRun=True)
```suggestion
        client.delete_volume(VolumeId=volume['VolumeId'])
```

2023-05-31 08:29 UTC, silvianahorga-al commented on alfresco-search-solr/volume_cleanup_lambda/volume_cleanup.py
> +        client.delete_volume(VolumeId=volume['VolumeId'], DryRun=True)
Removed DryRun
Files from  .history resulted after a terraform fmt I think. Pushed them by mistake so removed the files

2023-05-31 08:48 UTC, kylehodgetts approved these changes

2023-05-31 08:49 UTC, kylehodgetts approved these changes

2023-05-31 08:59 UTC, merged